name: Actions Workflow

on: 
  push: 
    branches: 
      - master
      #matches anything that starts with feature/ and has no additional slashes
      - 'feature/*' 
      # matches any number of slashes
      - 'releases/**'
      # ignore a branch 
      - '!releases/001'  
    # tags:
    #   - va.*
    # can also use paths 
    # paths:
      # - '**.js' 
      # - '!notthisone.js'  
      # - 'docs/**'   
  # repository_dispatch: #can be triggered manually - send post to URL
  #   types: [build-whatever]
  # schedule: 
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  # push:
  pull_request: 
    types: [closed, assigned, 
    opened, reopened]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: read payload
        run: echo ${{ github.event.client_payload.env}}
      - name: List Files 
        run: |
          pwd
          ls -a
          echo "the commit that started this workflow:"
          echo $GITHUB_SHA
          echo "the repository this is running for:"
          echo $GITHUB_REPOSITORY 
          echo "the GH workspace:"
          echo $GITHUB_WORKSPACE
          echo "github token:"
          echo "${{github.token}}"
        # just an example: not right way to do this
        #git clone git@github:$GITHUB_REPOSITORY 
        #git checkout $GITHUB_SHA
      - name: Checkout 
      # check out the current repo to the VM running the tasks      
        uses: actions/checkout@v1
      - name: List Files After Checkout
      # should see all the files are loaded onto the VM now
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        # github user/repo@{release | commit hash | branch}
        # https://github.com/actions/hello-world-javascript-action
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Stefano
        # access the output
      - name: Log Greeting Time 
        run: echo "${{steps.greet.outputs.time}}"
