name: Matrix
on: push
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [14,17]
      fail-fast: true
      max-parallel: 3  #0 default
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '${{ matrix.node_version }}'
      - run: |
          node -v
          echo 'node version: ${{ matrix.node_version }}'
