name: Matrix
on: pull_request
jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [14,17]
        exclude:
          - os: macos-latest 
            node_version: 14
          - os: windows-latest
            node_version: 14
        include:
          - os: ubuntu-latest
            node_version: 16
            is_ubuntu_16: "true"  
      fail-fast: true
      max-parallel: 3  #0 default
    runs-on: ${{ matrix.os }}
    env:
      is_ubuntu_16: ${{ matrix.is_ubuntu_8 }}
    steps:
      - uses: actions/setup-node@v2
        with: 
          node-version: '${{ matrix.node_version }}'
      - run: |
          node -v
          echo 'node version: ${{ matrix.node_version }}'
